#
# Makefile for trusty components
#

obj-$(CONFIG_TRUSTY)		+= trusty.o
obj-$(CONFIG_TRUSTY_SMC_ARM)	+= trusty-smc-arm.o
obj-$(CONFIG_TRUSTY_SMC_ARM64)	+= trusty-smc-arm64.o
obj-$(CONFIG_TRUSTY)		+= trusty-irq.o
obj-$(CONFIG_TRUSTY_LOG)	+= trusty-log.o
