# Makefile for the htc stability mechanism.
#

obj-$(CONFIG_DIRTY_SYSTEM_DETECTOR) += dirty_file_detector.o

obj-$(CONFIG_HTC_PROCESS_DEBUG) += htc_process_debug.o

# kallsyms-export
obj-$(CONFIG_KALLSYMS) += kallsyms-export.o

# bootmsg
obj-$(CONFIG_HTC_DEBUG_SAVE_BOOT_MSG) += bootmsg.o

obj-$(CONFIG_HTC_DEBUG_REPORT_MEMINFO) += htc_report_meminfo.o
