##############################################################################
# COPYRIGHT(C)	: Samsung Electronics Co.Ltd, 2006-2011 ALL RIGHTS RESERVED
#                 Makefile for ISDB-T for NMI Driver
##############################################################################
# VERSION&DATE	: Version 0.1
##############################################################################

obj-$(CONFIG_ISDBT_NMI)	+= nmi625.o nmi625-i2c.o

EXTRA_CFLAGS += -Idrivers/media/video
